### ISSUE TITLE
missing bio_new

### ISSUE THREAD

**Issue by bararchy** [randomstate/openssl_ext#2]
```
Error in line 1: while requiring "./spec/x509_spec.cr"

in spec/x509_spec.cr:30: instantiating 'OpenSSL::X509::Certificate.class#new(String)'

    from_pem = Certificate.new pem
                           ^~~

in src/openssl_ext/x509/certificate.cr:7: instantiating 'OpenSSL::GETS_BIO.class#new(IO::Memory)'

      bio = OpenSSL::GETS_BIO.new(io)
                              ^~~

in src/openssl_ext/bio.cr:27: undefined fun 'bio_new' for LibCrypto

    @bio = LibCrypto.bio_new(pointerof(GETS_BIO))

```

**Comment by bararchy** [comment]
@CImrie Maybe we should move this shard to the caring hands of https://github.com/crystal-community/ where multiple people can see and contribute to this shard and make it bigger, right now both @kingsleyh, myself and @omarroth have works around the OpenSSL bindings.
This will mean you will be given access to administer the repo, but we can transfer the ownership and co-manage PR's and overall work in a single location.

What do you think?

**Comment by bararchy** [comment]
who knows, maybe even the great @datanoise will come and help again a bit :)

**Comment by byfoz** [comment]
Hi @bararchy 
This is probably just down to the fact the shard hasn't been updated in 10 months (so won't be keeping pace with the current crystal version).

What would we need to do to get this over to the crystal-community so that we can get more people reaping its benefits and ideally moving a single shard forward for everyone?

**Comment by bararchy** [comment]
@CImrie Just do a Repo transfer to `crystal-community` 
You can follow those instructions: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-a-repository-to-another-user-account-or-to-an-organization

**Comment by kingsleyh** [comment]
There are 3 versions of OpenSSL
  * 1.0 -> previously LTS but now expires Dec 2019 (security fixes only)
  * 1.1  -> expires Sep 2019 (security fixes only)
  * 1.1.1  -> current LTS until 2023 (active development)

Although 1.1.1a is the recommended version and upgrading from other versions is recommended - many of the operating systems still use the earlier version by default and upgrading everywhere is not always convenient.

Also to bear in mind are the Operating Systems that should be supported and what the default versions of OpenSSL are on the ones we choose to support.

I'm certainly willing to contribute the work I've done on ECDSA bindings to a single shard but I'd like to know more about the overall structure of the shard and some of these questions:

 1. what will the overall skeleton look like - and will it be following the Ruby API? or something other API?

2. Will we write wrappers in C to abstract the functionality into a nicer API for Crystal? or write the wrapper in Crystal and use the bindings directly in Crystal code to build an API?

3. When I tried to set the LD_FLAGS in my bindings to a local ext directory with 1.1.1a and at the same time `require "openssl"` which picked up the default 1.0.2q on my system - my binding did not end up using the 1.1.1a version and after trying many things I could not get it to work. To resolve this I upgraded my system version to 1.1.1.a and ditched the ext approach. But then I found it very inconvenient to upgrade all the places that might use my code to 1.1.1a (and force every user to also) so I switched writing the code to use the older functions. How should we handle this kind of thing?

Probably many other questions but thats it for now :)

**Comment by bararchy** [comment]
@kingsleyh @CImrie hearing @RX14 and other core team members , they said the best course of action is PRing directly to crystal-lang/crystal

**Comment by bararchy** [comment]
So, my main question is this, @CImrie , can you make the specs pass with latest Crystal? if you can fix it I'll take the work and prepare a PR (unless you wish to do it) of all the changes and additions directly into crystal's repo

**Comment by byfoz** [comment]
@bararchy there is also still the issue on the readme:
> Encoding with a passphrase is not yet supported as OpenSSL fails silently without any errors (in order to fix).

There are some additional comments in `rsa_spec.cr` for testing whether this is fixed or not - but I don't have any knowledge of the inner workings of OpenSSL to know why it's failing at this point.

The shard is also not set up to support a variety of versions of OpenSSL as @kingsleyh pointed out. Do you think this should be sorted before / after merging into stdlib?

I will spend some time making it pass with the current version of Crystal as it stands at the moment. If it's desirable to fix the two above issues before PR'ing then I'd appreciate some help with those if possible. 

Happy at that point for either one of us to PR it into the stdlib 🎉

**Comment by bararchy** [comment]
@CImrie I asked @RX14 about version support, he specified we should only care about `1.0.2`,`1.1.0` and `1.1.1`. 


Regarding above issues, Knowing crystal and the PR-to-merge cycle the smaller and simpler we can make a PR the faster it will be o merge, so we better start with something like "Add functionality to Certificate and RSA" and we can continue working from there with small and directed PRs.

**Comment by noellabo** [comment]
I was worried about errors, so I wrote a fix.

It will work with OpenSSL 1.0.2, but because it is not solving the essential problem in 1.1 and later it should not work yet.

**Comment by byfoz** [comment]
@bararchy, @noellabo has been a saint and made the library compile with the new crystal version. 
It would be fantastic if you are able to get time to work some magic and submit this to merge into the core stdlib 🎉

**Comment by bararchy** [comment]
@CImrie Will do! thanks for the ping

**Comment by noellabo** [comment]
@CImrie Now apply v0.1.2 tag to use with shards.
It should help existing projects correspond to crystal 0.27.0 or later.

**Comment by byfoz** [comment]
Thanks for the reminder @noellabo 👍
